### ISSUE TITLE
Unable to save credentials

### ISSUE THREAD

**Issue by tormjens** [fxpio/tug#3]
I love the premise of this application. It matches what I'm trying to do exactly, and takes it one step further.

However, when setting this up, I am unable to save my IAM credentials through the admin panel?

I might be too eager and the application isn't deployed completely yet. Is everything OK when CloudFOrmation says "CREATE_COMPLETE" ?

Should I just wait?

When saving it just says "Forbidden".

**Comment by tormjens** [comment]
Stupid me. It worked all of a sudden.

**Comment by francoispluchino** [comment]
Yes, you have to wait until all the services are initialized. So you get as many `CREATE_COMPLETE` events as there are services (around 13 its seems to me).
